# Generated by Django 5.1.6 on 2025-02-24 03:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_similarity', models.FloatField()),
                ('text_similarity', models.FloatField()),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=20)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
