# Generated by Django 5.1.6 on 2025-02-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatch',
            name='missing_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.missingreport'),
        ),
        migrations.AddField(
            model_name='aimatch',
            name='sighting_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.sightingreport'),
        ),
    ]
