# Generated by Django 5.1.6 on 2025-02-27 07:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryReport',
            fields=[
                ('discovery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('found_time', models.DateTimeField()),
                ('found_latitude', models.FloatField()),
                ('found_longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='MissingReport',
            fields=[
                ('missing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FOUND', 'Đã tìm thấy'), ('MISSING', 'Đang mất tích'), ('SEARCHING', 'Đang tìm kiếm')], default='MISSING', max_length=50)),
                ('lost_time', models.DateTimeField()),
                ('lost_latitude', models.FloatField()),
                ('lost_longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Matching_Result',
            fields=[
                ('matching_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_score', models.FloatField()),
                ('description_score', models.FloatField()),
                ('status_matching', models.CharField(choices=[('FOUND', 'Đã tìm thấy'), ('MISSING', 'Đang mất tích'), ('SEARCHING', 'Đang tìm kiếm')], default='SEARCHING', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discovery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.discoveryreport')),
                ('missing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.missingreport')),
            ],
        ),
    ]
