# Generated by Django 5.1.6 on 2025-02-24 03:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('sighting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('photo_url', models.URLField()),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MissingReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], max_length=20)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_members.familymember')),
            ],
        ),
    ]
