# Generated by Django 5.1.6 on 2025-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='face_encoding',
        ),
        migrations.AddField(
            model_name='familymember',
            name='face_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
