# Generated by Django 5.1.6 on 2025-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0003_remove_familymember_face_encoding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='user',
            new_name='user_id',
        ),
    ]
